base_url = "https://woojiq.github.io/"
title = "woojiq's blog"
default_language = "en"

generate_feed = false
compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "inspired-github"
external_links_target_blank = true
smart_punctuation = true

[extra]
date_format="%d %b, %Y"
hide_made_with_line = true

[[extra.main_menu]]
name = "Home"
url = ""

[[extra.main_menu]]
name = "About"
url = "@/about.md"
